name: socket_io_endpoint
description: The Socket.IO server implementation for this tutorial
version: 1.0.0

environment:
  sdk: ">=2.18.4 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  socket_io: ^1.0.1
